# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BWSI Project Report
email: augustt198@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Project report of the 2016 Beaverworks summer institute by August Trollbäck and Max Krieger.
baseurl: "/bwsi-report" # the subpath of your site, e.g. /blog
url: "http://augustt198.github.io" # the base hostname & protocol for your site
github_username:  augustt198 & maxkrieger

# Build settings
markdown: kramdown
